### ISSUE TITLE
currentInfoClass repeats copy when more than 1 CSS class applied

### ISSUE THREAD

**Issue by extractachris** [ginader/Accessible-Tabs#40]
If I apply more than one class to  the `currentInfoClass` option:

```
currentInfoClass: 'current-info  visuallyhidden'
```

and then click on a `tabhead` link multiple times in my markup, the "current tab:" copy is repeated in the dom:

```
<li class="first current" id="accessibletabsnavigation0-0">
    <a class="headline js-tab-label" href=
    "#accessibletabscontent0-0"><span class=
    "current-info visuallyhidden">current tab:</span> <span class=
    "current-info visuallyhidden">current tab:</span> <span class=
    "current-info visuallyhidden">current tab:</span> <span class=
    "current-info visuallyhidden">current tab:</span> <span class=
    "current-info visuallyhidden">current tab:</span> Tab 1</a>
</li>
```

**Comment by ginader** [comment]
I understand the issue. For now I'd say: don't use multiple classes. Further I'm also looking into changing/extending this to support multiple classes / an array of classes.

**Comment by ginader** [comment]
Fixed in the new release v1.9.9. 
Each of the classname options can now contain multiple classnames divided by a space i.e.: currentInfoClass: 'current-info visuallyhidden'
You can see a working demo here: http://blog.ginader.de/dev/jquery/accessible-tabs/simple-multiple-currentinfoclass.html

**Comment by extractachris** [comment]
:+1:

**Comment by ginader** [comment]
🙂
