### ISSUE TITLE
Error with IE7 : 

### ISSUE THREAD

**Issue by mgazanayi** [ginader/Accessible-Tabs#45]
Hello,
First of all thanks for your lib.

I tried this example http://blog.ginader.de/dev/jquery/accessible-tabs/simple.html on IE 7 and I got this error:

```
Syntax error, unrecognized expression: http://blog.ginader.de/dev/jquery/accessible-tabs/simple.html#accessibletabscontent0-2
``` 

We have the same issue on our project which uses your library and because we have important clients using IE 7, we are stuck on that and can't say: we don't support IE 7...

Any idea about this ?

Thanks in advance.

**Comment by melanieberrut** [comment]
I'm facing the exact same issue. IE8 works fine, but not on IE7.

**Comment by ginader** [comment]
So happy to see that folks are still using this! 
But then I'm also shocked to hear that you still have to support IE7. Very sorry for you guys! 
I just tried to download a IE7 VM to reproduce the errors you described but it turns out that Microsoft is no longer offering a IE7 VM: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ — IE8 is the oldest I can get. Sorry :-(

**Comment by mgazanayi** [comment]
Hey! thanks for your support. For ie7, we have client's that are developing products on top of our APIs and who must support ie7 and of course it's transitive, :(

Yes, there is no longer a VM having IE7 but you can try under an ie8 and switch on Browser Mode : IE 7 on developer tools, that reproduces the problem :)

**Comment by ginader** [comment]
Have you tried some of the older releases?
You can find them here: https://github.com/ginader/Accessible-Tabs/releases
The newer releases contain changes to accommodate newer jQuery versions so maybe an older release would work better for you?

**Comment by mgazanayi** [comment]
Yes I tried an old version and the latest one.

I edited the library to remove the add of # when construction the href element, and that works, it removes the error, but the problem is that, when you access the first time to the web page using an anchor, it doesn't open the corresponding tab.

**Comment by ginader** [comment]
Good tip about IE7 Browser mode in IE8! Downloading that one now.

**Comment by mgazanayi** [comment]
I just tried the 1.9.5 version and I think it's working. I'll do more tests to confirm that.

T.H.A.N.K.S

**Comment by ginader** [comment]
WOOHOOO! That's EXCELLENT news! Let me know how it progresses and also make sure you're using jQuery 1.12 https://code.jquery.com/jquery/#jquery-all-1.x (which my demo code does not which is probably causing the Sizzle error)

**Comment by mgazanayi** [comment]
For jQuery, it's the version we are using. Thanks for mentioning it!
Well, it seems to work using the compatibility mode, I'll try at work in a dry aged embedded ie7 browser and tell you if it is okey :)

Thanks again for you reactivity!

**Comment by melanieberrut** [comment]
Hey guys, if you want a VM with IE7, you can download a VM running Vista that has IE7 here: https://gist.github.com/zmwangx/e728c56f428bc703c6f6
With that dont need to use compatibility mode.

**Comment by mgazanayi** [comment]
Thanks @melanieberrut but they really deleted them: `The specified resource does not exist. RequestId:31ea3adf-001e-00d0-79f4-89878d000000 Time:2018-01-10T09:20:13.0641865Z` when trying to download : https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE7/Mac/IE7.Vista.For.Mac.VirtualBox.zip

**Comment by melanieberrut** [comment]
It was working about 2 month ago, when I went to download it...
Good thing you are on a mac using VB as well. I've just uploaded my zipped download to the cloud, you can download it from here https://transfer.pcloud.com/download.html?code=5ZTyep7ZIKounXwFV2SZfLC4ZFrTQuXbezPBULKNpLLB0hHDNP1OX

**Comment by mgazanayi** [comment]
@melanieberrut: Wow, really nice from you! Thanks!

**Comment by melanieberrut** [comment]
Is the solution to downgrade to jquery 1.9.5 for this to work in IE7 ?

**Comment by mgazanayi** [comment]
Sorry for the delay, yes, it's working using jQuery 1.12.4 and accessible tabs 1.9.5. Thanks a lot.
